# -*- coding: utf-8 -*-
"""Road accident project - APSSDC (ML)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bYAnMyCDWRbJ0YFXCAvIN-3kD2udoCY
"""

# ======================================================
# ROAD ACCIDENT SEVERITY PREDICTION SYSTEM
# Step 1 : Import Libraries
# ======================================================

# Install required libraries
!pip install xgboost gradio -q

# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# XGBoost
from xgboost import XGBClassifier

# Save model
import pickle

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

print(" All libraries imported successfully.")

#STEP 2: Upload Dataset
from google.colab import files

uploaded = files.upload()

#STEP 3: Read Dataset
df = pd.read_csv("road_accident_dataset_v2_realistic.csv")

print("Dataset Loaded Successfully!")

df.head()

#STEP 4: Understand the Dataset
print("="*60)
print("Dataset Shape")
print(df.shape)

print("\n")

print("="*60)
print("Column Names")
print(df.columns)

print("\n")

print("="*60)
print("Dataset Information")
print("="*60)
df.info()

#STEP 5: Check Missing Values
print(df.isnull().sum())

#STEP 6: Check Duplicate Records
print("Duplicate Records :", df.duplicated().sum())

#STEP 7: Target Distribution
df["accident_severity"].value_counts()

#STEP 8: First Visualization
plt.figure(figsize=(6,4))

sns.countplot(
    data=df,
    x="accident_severity",
    palette="viridis"
)

plt.title("Accident Severity Distribution")
plt.xlabel("Severity")
plt.ylabel("Count")

plt.show()

#STEP 9: Select Only Required Features
selected_features = [
    "weather",
    "road_type",
    "traffic_density",
    "visibility",
    "vehicles_involved",
    "hour"
]

# ===========================================
# Step 10 : Feature Selection
# ===========================================

X = df[[
    "weather",
    "road_type",
    "traffic_density",
    "visibility",
    "vehicles_involved",
    "hour"
]]

y = df["accident_severity"]

print("Feature Shape :", X.shape)
print("Target Shape :", y.shape)

X.head()

#Step 11 – Encode Categorical Features
categorical_columns = [
    "weather",
    "road_type",
    "traffic_density"
]

feature_encoder = OrdinalEncoder()

X[categorical_columns] = feature_encoder.fit_transform(
    X[categorical_columns]
)

print("Categorical Features Encoded Successfully")

# Step 12 – Encode Target Column

#Convert:Minor → 0,Major → 1,Fatal → 2
target_encoder = LabelEncoder()

y = target_encoder.fit_transform(y)

print("Target Encoded Successfully")
print(target_encoder.classes_)

#Step 13 – Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Data :", X_train.shape)
print("Testing Data :", X_test.shape)

#step 14 – Train XGBoost Model
model = XGBClassifier(

    n_estimators=300,

    learning_rate=0.05,

    max_depth=6,

    random_state=42,

    eval_metric="mlogloss"

)

model.fit(X_train, y_train)

print("Model Trained Successfully")

#step 15 – Make Predictions
y_pred = model.predict(X_test)

#step 16 - Accuracy
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy : {accuracy*100:.2f}%")

#step 17 – Classification Report
print(classification_report(y_test, y_pred))

#step 18 Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=target_encoder.classes_,
    yticklabels=target_encoder.classes_
)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Confusion Matrix")

plt.show()

#step 19 – Save Model
pickle.dump(model, open("road_accident_model.pkl", "wb"))

pickle.dump(feature_encoder, open("feature_encoder.pkl", "wb"))

pickle.dump(target_encoder, open("target_encoder.pkl", "wb"))

print("Model Saved Successfully")

#step 19(b)- download model files
from google.colab import files

files.download("road_accident_model.pkl")
files.download("feature_encoder.pkl")
files.download("target_encoder.pkl")

#step 20 – Import Widgets
import ipywidgets as widgets
from IPython.display import display, Markdown
import pandas as pd
import numpy as np

#step 21 – Create Input Widgets
weather = widgets.Dropdown(
    options=["Clear","Sunny","Cloudy","Rain","Heavy Rain","Fog","Storm"],
    value="Rain",
    description="Weather:"
)

road_type = widgets.Dropdown(
    options=["urban","rural","highway"],
    value="highway",
    description="Road:"
)

traffic = widgets.Dropdown(
    options=["Low","Medium","High"],
    value="High",
    description="Traffic:"
)

visibility = widgets.IntSlider(
    value=500,
    min=50,
    max=2000,
    step=50,
    description="Visibility"
)

vehicles = widgets.IntSlider(
    value=2,
    min=1,
    max=5,
    description="Vehicles"
)

hour = widgets.IntSlider(
    value=18,
    min=0,
    max=23,
    description="Hour"
)

predict_button = widgets.Button(
    description=" Predict Severity",
    button_style="success"
)

output = widgets.Output()

#step 22 – Prediction Function
def predict_clicked(b):

    output.clear_output()

    # Create input dataframe
    sample = pd.DataFrame({

        "weather":[weather.value],
        "road_type":[road_type.value],
        "traffic_density":[traffic.value],
        "visibility":[visibility.value],
        "vehicles_involved":[vehicles.value],
        "hour":[hour.value]

    })

    # Encode categorical columns
    sample[categorical_columns] = feature_encoder.transform(
        sample[categorical_columns]
    )

    # Prediction
    prediction = model.predict(sample)
    probabilities = model.predict_proba(sample)

    confidence = np.max(probabilities) * 100

    result = target_encoder.inverse_transform(prediction)[0]

    # Probability of all classes
    classes = target_encoder.classes_
    prob_dict = dict(zip(classes, probabilities[0] * 100))

    # Risk Level & Safety Tips
    if result == "minor":

        severity = " MINOR ACCIDENT"
        risk = " LOW"

        tips = [
            "Follow Speed Limits",
            "Drive Carefully",
            "Wear Seat Belt",
            "Avoid Mobile Phone Usage",
            "Follow Traffic Signals"
        ]

    elif result == "major":

        severity = " MAJOR ACCIDENT"
        risk = " MEDIUM"

        tips = [
            "Reduce Speed",
            "Maintain Safe Distance",
            "Avoid Overtaking",
            "Wear Seat Belt",
            "Drive Carefully"
        ]

    else:

        severity = " FATAL ACCIDENT"
        risk = " HIGH"

        tips = [
            "Avoid Travelling if Possible",
            "Drive Slowly",
            "Use Fog Lights",
            "Wear Seat Belt",
            "Call Emergency Services if Needed"
        ]

    with output:

        display(Markdown("#  Road Accident Severity Prediction Result"))

        display(Markdown(f"## {severity}"))

        display(Markdown(f"###  Confidence Score : **{confidence:.2f}%**"))

        display(Markdown(f"###  Risk Level : **{risk}**"))

        display(Markdown("---"))

        display(Markdown("##  Prediction Probabilities"))

        display(Markdown(f" **Minor : {prob_dict['minor']:.2f}%**"))

        display(Markdown(f" **Major : {prob_dict['major']:.2f}%**"))

        display(Markdown(f" **Fatal : {prob_dict['fatal']:.2f}%**"))

        display(Markdown("---"))

        display(Markdown("##  Prediction Summary"))

        display(Markdown(
            f"""
Based on the selected road conditions, the trained **XGBoost Machine Learning Model**
predicts that the accident severity is most likely:

# {severity}
"""
        ))

        display(Markdown("---"))

        display(Markdown("## Safety Recommendations"))

        for tip in tips:
            display(Markdown(f"✔ {tip}"))

        display(Markdown("---"))

        display(Markdown("##  Drive Safe! Your Safety is Our Priority "))

#step 23 – Connect Button
predict_button.on_click(predict_clicked)

#step 24 – Display Interface
display(weather)
display(road_type)
display(traffic)
display(visibility)
display(vehicles)
display(hour)

display(predict_button)

display(output)

"""from here gradio will be implemented"""

#Install libraries
!pip install gradio xgboost scikit-learn -q

#Upload your 3 pkl files (new cell):
from google.colab import files
files.upload()
# Select: road_accident_model.pkl, feature_encoder.pkl, target_encoder.pkl

# ============================================================
# 🚗 ROAD ACCIDENT SEVERITY PREDICTOR
# Professional Single-Page Gradio Application
# Gradio 6.19.0 Compatible
# ============================================================

import pickle
import warnings
import numpy as np
import pandas as pd
import gradio as gr

warnings.filterwarnings("ignore")


# ============================================================
# 1. LOAD TRAINED MODEL
# ============================================================

model = pickle.load(open("road_accident_model.pkl", "rb"))
feature_encoder = pickle.load(open("feature_encoder.pkl", "rb"))
target_encoder = pickle.load(open("target_encoder.pkl", "rb"))

print("✅ Model loaded successfully!")


# ============================================================
# 2. PROJECT CONFIGURATION
# ============================================================

FEATURE_ORDER = [
    "weather",
    "road_type",
    "traffic_density",
    "visibility",
    "vehicles_involved",
    "hour"
]

CAT_COLS = [
    "weather",
    "road_type",
    "traffic_density"
]


# ============================================================
# 3. SAFETY RECOMMENDATIONS
# ============================================================

TIPS = {

    "minor": [
        "✔ Follow speed limits at all times",
        "✔ Avoid mobile phone usage while driving",
        "✔ Always wear your seat belt",
        "✔ Follow all traffic signals carefully",
        "✔ Stay alert and avoid distractions"
    ],

    "major": [
        "✔ Reduce your speed immediately",
        "✔ Maintain a safe following distance",
        "✔ Do not attempt overtaking",
        "✔ Wear your seat belt at all times",
        "✔ Stay extra alert at all junctions"
    ],

    "fatal": [
        "✔ Avoid travelling in these conditions if possible",
        "✔ Drive very slowly and with extreme caution",
        "✔ Use fog lights when visibility is poor",
        "✔ Wear your seat belt — it saves lives",
        "✔ Call emergency services immediately if needed"
    ]
}


# ============================================================
# 4. RESULT DESIGN
# ============================================================

CONFIG = {

    "minor": {
        "title": "🟢 MINOR ACCIDENT",
        "color": "#16a34a",
        "bg": "#f0fdf4",
        "border": "#86efac",
        "risk": "🟢 LOW RISK",
        "rbg": "#dcfce7",
        "rcol": "#15803d"
    },

    "major": {
        "title": "🟠 MAJOR ACCIDENT",
        "color": "#d97706",
        "bg": "#fffbeb",
        "border": "#fcd34d",
        "risk": "🟠 MEDIUM RISK",
        "rbg": "#fef3c7",
        "rcol": "#b45309"
    },

    "fatal": {
        "title": "🔴 FATAL ACCIDENT",
        "color": "#dc2626",
        "bg": "#fef2f2",
        "border": "#fca5a5",
        "risk": "🔴 HIGH RISK",
        "rbg": "#fee2e2",
        "rcol": "#b91c1c"
    }
}


# ============================================================
# 5. CORE PREDICTION FUNCTION
# ============================================================

def run_prediction(
    weather,
    road_type,
    traffic_density,
    visibility,
    vehicles_involved,
    hour
):

    # --------------------------------------------------------
    # Create input dataframe
    # --------------------------------------------------------

    row = pd.DataFrame([{

        "weather": weather,

        "road_type": road_type,

        "traffic_density": traffic_density,

        "visibility": float(visibility),

        "vehicles_involved": int(vehicles_involved),

        "hour": int(hour)

    }])[FEATURE_ORDER]


    # --------------------------------------------------------
    # Encode categorical values
    # --------------------------------------------------------

    row[CAT_COLS] = feature_encoder.transform(row[CAT_COLS])


    # --------------------------------------------------------
    # Model prediction
    # --------------------------------------------------------

    probabilities = model.predict_proba(row)[0]

    prediction_index = int(np.argmax(probabilities))

    predicted_class = target_encoder.inverse_transform(
        [prediction_index]
    )[0]

    confidence = round(
        float(probabilities[prediction_index]) * 100,
        2
    )


    # --------------------------------------------------------
    # Get configuration
    # --------------------------------------------------------

    cfg = CONFIG[predicted_class]

    tips = TIPS[predicted_class]


    # --------------------------------------------------------
    # Probability table
    # --------------------------------------------------------

    classes = target_encoder.classes_

    probability_df = pd.DataFrame({

        "Severity": [
            c.upper()
            for c in classes
        ],

        "Probability (%)": [
            round(float(p) * 100, 2)
            for p in probabilities
        ]

    })

    probability_df = probability_df.sort_values(
        "Probability (%)",
        ascending=False
    ).reset_index(drop=True)


    # --------------------------------------------------------
    # Safety recommendations HTML
    # --------------------------------------------------------

    tips_html = ""

    for tip in tips:

        tips_html += f"""
        <div class="tip-item"
             style="
             color:#334155;
             border-bottom:1px solid {cfg['border']};
             ">
            {tip}
        </div>
        """


    # --------------------------------------------------------
    # Result HTML
    # --------------------------------------------------------

    result = f"""

    <div class="result-card"
         style="
         background:{cfg['bg']};
         border:2px solid {cfg['border']};
         ">

        <!-- RESULT HEADER -->

        <div class="result-header"
             style="
             background:{cfg['color']};
             ">

            <div class="result-title">
                {cfg['title']}
            </div>

            <div class="result-subtitle">
                Prediction based on the selected road conditions
            </div>

        </div>


        <!-- RESULT BODY -->

        <div class="result-body">


            <!-- CONFIDENCE -->

            <div class="info-card">

                <div class="info-heading">
                    📈 Confidence Score
                </div>

                <div class="confidence-value"
                     style="
                     color:{cfg['color']};
                     ">

                    {confidence}%

                </div>

                <div class="progress-background">

                    <div class="progress-fill"
                         style="
                         width:{confidence}%;
                         background:{cfg['color']};
                         ">
                    </div>

                </div>

            </div>


            <!-- RISK LEVEL -->

            <div class="risk-card"
                 style="
                 background:{cfg['rbg']};
                 border:1px solid {cfg['border']};
                 ">

                <span class="risk-label">
                    ⚠️ Risk Level
                </span>

                <span class="risk-value"
                      style="
                      color:{cfg['rcol']};
                      ">

                    {cfg['risk']}

                </span>

            </div>


            <!-- SAFETY RECOMMENDATIONS -->

            <div class="safety-card"
                 style="
                 border:1px solid {cfg['border']};
                 ">

                <div class="safety-heading"
                     style="
                     color:{cfg['color']};
                     ">

                    🛡️ Safety Recommendations

                </div>

                <div class="tips-container">

                    {tips_html}

                </div>

            </div>


        </div>

    </div>
    """

    return result, probability_df


# ============================================================
# 6. PREDICTION WRAPPER
# ============================================================

def predict(
    weather,
    road_type,
    traffic_density,
    visibility,
    vehicles_involved,
    hour
):

    return run_prediction(
        weather,
        road_type,
        traffic_density,
        visibility,
        vehicles_involved,
        hour
    )


# ============================================================
# 7. QUICK EXAMPLE FUNCTIONS
# ============================================================

def example_rainy_highway():

    vals = [
        "Rain",
        "highway",
        "High",
        300,
        4,
        18
    ]

    result, prob = run_prediction(*vals)

    return *vals, result, prob


def example_foggy_road():

    vals = [
        "Fog",
        "rural",
        "Low",
        80,
        2,
        6
    ]

    result, prob = run_prediction(*vals)

    return *vals, result, prob


def example_night_driving():

    vals = [
        "Clear",
        "urban",
        "Low",
        200,
        1,
        23
    ]

    result, prob = run_prediction(*vals)

    return *vals, result, prob


def example_heavy_traffic():

    vals = [
        "Cloudy",
        "urban",
        "High",
        600,
        4,
        9
    ]

    result, prob = run_prediction(*vals)

    return *vals, result, prob


def example_dangerous():

    vals = [
        "Heavy Rain",
        "highway",
        "High",
        150,
        5,
        19
    ]

    result, prob = run_prediction(*vals)

    return *vals, result, prob


# ============================================================
# 8. PROFESSIONAL LIGHT UI CSS
# ============================================================

CSS = """

/* =========================================================
   MAIN PAGE
   ========================================================= */

body {
    background: #eef5ff !important;
}

.gradio-container {

    max-width: 1250px !important;

    width: 97% !important;

    margin: 0 auto !important;

    padding: 12px !important;

    background: #eef5ff !important;

    color: #1e293b !important;

    font-family:
        "Segoe UI",
        Arial,
        sans-serif !important;


    /* Force Gradio light variables */

    --body-text-color: #1e293b !important;

    --body-text-color-subdued: #64748b !important;

    --block-label-text-color: #1e3a8a !important;

    --block-title-text-color: #1e3a8a !important;

    --input-text-color: #1e293b !important;

    --input-background-fill: #ffffff !important;

    --block-background-fill: #ffffff !important;

    --block-border-color: #dbeafe !important;
}


/* =========================================================
   HEADER
   ========================================================= */

#app-header {

    background:
        linear-gradient(
            135deg,
            #1d4ed8,
            #2563eb,
            #3b82f6
        ) !important;

    border-radius: 18px !important;

    padding: 18px 20px !important;

    text-align: center !important;

    margin-bottom: 14px !important;

    box-shadow:
        0 8px 25px
        rgba(37, 99, 235, 0.25) !important;
}


#app-header h1 {

    color: #ffffff !important;

    font-size: 28px !important;

    font-weight: 900 !important;

    margin: 0 !important;

}


#app-header p {

    color: #dbeafe !important;

    font-size: 14px !important;

    margin: 6px 0 0 0 !important;

}


/* =========================================================
   MAIN CARDS
   ========================================================= */

.left-panel,
.right-panel {

    background: #ffffff !important;

    border: 1px solid #dbeafe !important;

    border-radius: 18px !important;

    padding: 20px !important;

    box-shadow:
        0 5px 20px
        rgba(30, 64, 175, 0.10) !important;

}


/* =========================================================
   SECTION HEADINGS
   ========================================================= */

.section-head {

    background: #eff6ff !important;

    color: #1d4ed8 !important;

    border-left:
        6px solid #2563eb !important;

    border-radius: 10px !important;

    padding: 11px 14px !important;

    margin-bottom: 14px !important;

    font-size: 17px !important;

    font-weight: 800 !important;

}


/* =========================================================
   LABELS
   ========================================================= */

.left-panel label,
.right-panel label {

    color: #1e293b !important;

}


.left-panel label span,
.right-panel label span {

    color: #1e3a8a !important;

    font-weight: 700 !important;

    font-size: 14px !important;

}


/* =========================================================
   DROPDOWN
   ========================================================= */

.left-panel .gr-dropdown {

    background: #ffffff !important;

    color: #1e293b !important;

    border:
        1px solid #bfdbfe !important;

    border-radius: 10px !important;

}


/* Dropdown text */

.left-panel .gr-dropdown *,
.left-panel select {

    color: #1e293b !important;

}


/* Dropdown selected value */

.left-panel .gr-input {

    background: #ffffff !important;

    color: #1e293b !important;

}


/* =========================================================
   INPUT BOXES
   ========================================================= */

.left-panel input {

    background: #ffffff !important;

    color: #1e293b !important;

    border:
        1px solid #bfdbfe !important;

    border-radius: 9px !important;

    font-weight: 600 !important;

}


/* Placeholder */

.left-panel input::placeholder {

    color: #94a3b8 !important;

}


/* =========================================================
   SLIDERS
   ========================================================= */

.left-panel input[type="range"] {

    accent-color: #2563eb !important;

}


/* Slider value */

.left-panel .range-value,
.left-panel .range-label {

    color: #1e293b !important;

    font-weight: 700 !important;

}


/* =========================================================
   PREDICT BUTTON
   ========================================================= */

#predict-btn {

    width: 100% !important;

    background:
        linear-gradient(
            135deg,
            #2563eb,
            #1d4ed8
        ) !important;

    color: #ffffff !important;

    border: none !important;

    border-radius: 12px !important;

    font-size: 18px !important;

    font-weight: 800 !important;

    padding: 13px !important;

    margin-top: 10px !important;

    box-shadow:
        0 6px 18px
        rgba(37,99,235,0.30) !important;

    transition: 0.2s ease !important;

}


#predict-btn:hover {

    transform: translateY(-2px) !important;

    box-shadow:
        0 10px 25px
        rgba(37,99,235,0.40) !important;

}


/* =========================================================
   QUICK EXAMPLE BUTTONS
   ========================================================= */

.ex-btn {

    background: #f8fbff !important;

    border:
        1px solid #bfdbfe !important;

    color: #1d4ed8 !important;

    border-radius: 10px !important;

    font-weight: 700 !important;

}


.ex-btn:hover {

    background: #eff6ff !important;

    border-color: #60a5fa !important;

}


/* =========================================================
   RESULT CARD
   ========================================================= */

.result-card {

    border-radius: 16px !important;

    overflow: hidden !important;

    box-shadow:
        0 5px 20px
        rgba(15,23,42,0.08) !important;

}


.result-header {

    padding: 18px !important;

    text-align: center !important;

}


.result-title {

    color: #ffffff !important;

    font-size: 23px !important;

    font-weight: 900 !important;

}


.result-subtitle {

    color:
        rgba(255,255,255,0.90) !important;

    font-size: 13px !important;

    margin-top: 5px !important;

}


.result-body {

    padding: 18px !important;

}


/* =========================================================
   CONFIDENCE
   ========================================================= */

.info-card {

    background: #ffffff !important;

    border:
        1px solid #e2e8f0 !important;

    border-radius: 12px !important;

    padding: 15px !important;

    margin-bottom: 12px !important;

}


.info-heading {

    color: #334155 !important;

    font-size: 15px !important;

    font-weight: 800 !important;

}


.confidence-value {

    font-size: 26px !important;

    font-weight: 900 !important;

    margin: 6px 0 8px 0 !important;

}


.progress-background {

    width: 100% !important;

    height: 11px !important;

    background: #e2e8f0 !important;

    border-radius: 999px !important;

    overflow: hidden !important;

}


.progress-fill {

    height: 100% !important;

    border-radius: 999px !important;

}


/* =========================================================
   RISK
   ========================================================= */

.risk-card {

    border-radius: 12px !important;

    padding: 14px !important;

    display: flex !important;

    justify-content: space-between !important;

    align-items: center !important;

    margin-bottom: 12px !important;

}


.risk-label {

    color: #334155 !important;

    font-size: 15px !important;

    font-weight: 700 !important;

}


.risk-value {

    font-size: 17px !important;

    font-weight: 900 !important;

}


/* =========================================================
   SAFETY
   ========================================================= */

.safety-card {

    background: #ffffff !important;

    border-radius: 12px !important;

    padding: 15px !important;

}


.safety-heading {

    font-size: 17px !important;

    font-weight: 900 !important;

    padding-bottom: 10px !important;

    border-bottom: 1px solid #e2e8f0 !important;

    margin-bottom: 5px !important;

}


.tip-item {

    padding: 8px 3px !important;

    font-size: 14px !important;

    font-weight: 600 !important;

}


/* =========================================================
   PROBABILITY TABLE
   ========================================================= */

.right-panel .gr-dataframe {

    background: #ffffff !important;

    border-radius: 12px !important;

}


.right-panel .gr-dataframe * {

    color: #1e293b !important;

}


/* =========================================================
   FOOTER
   ========================================================= */

#app-footer {

    background: #ffffff !important;

    border:
        1px solid #dbeafe !important;

    border-radius: 12px !important;

    text-align: center !important;

    padding: 12px !important;

    margin-top: 12px !important;

    color: #64748b !important;

    font-size: 13px !important;

}


/* =========================================================
   MOBILE RESPONSIVE
   ========================================================= */

@media (max-width: 800px) {

    .gradio-container {

        width: 96% !important;

        padding: 6px !important;

    }

    #app-header h1 {

        font-size: 22px !important;

    }

    .left-panel,
    .right-panel {

        padding: 14px !important;

    }

}
"""


# ============================================================
# 9. BUILD GRADIO APPLICATION
# ============================================================

with gr.Blocks(
    css=CSS,
    theme=gr.themes.Soft(
        primary_hue="blue",
        secondary_hue="blue",
        neutral_hue="gray"
    ),
    title="🚗 Road Accident Severity Predictor"
) as app:


    # ========================================================
    # HEADER
    # ========================================================

    gr.HTML("""
    <div id="app-header">

        <h1>
            🚗 Road Accident Severity Predictor
        </h1>

        <p>
            Using Machine Learning to Predict Accident Severity
        </p>

    </div>
    """)


    # ========================================================
    # MAIN TWO-COLUMN LAYOUT
    # ========================================================

    with gr.Row(
        equal_height=False
    ):


        # ====================================================
        # LEFT SIDE — USER INPUT
        # ====================================================

        with gr.Column(
            scale=5,
            elem_classes="left-panel"
        ):


            gr.HTML("""
            <div class="section-head">
                📝 Enter Accident Conditions
            </div>
            """)


            # -----------------------------------------------
            # WEATHER
            # -----------------------------------------------

            weather = gr.Dropdown(

                choices=[
                    "Clear",
                    "Sunny",
                    "Cloudy",
                    "Rain",
                    "Heavy Rain",
                    "Fog",
                    "Storm"
                ],

                value="Clear",

                label="🌦️ Weather Condition"
            )


            # -----------------------------------------------
            # ROAD TYPE
            # -----------------------------------------------

            road_type = gr.Dropdown(

                choices=[
                    "urban",
                    "rural",
                    "highway"
                ],

                value="urban",

                label="🛣️ Road Type"
            )


            # -----------------------------------------------
            # TRAFFIC DENSITY
            # -----------------------------------------------

            traffic_density = gr.Dropdown(

                choices=[
                    "Low",
                    "Medium",
                    "High"
                ],

                value="Medium",

                label="🚗 Traffic Density"
            )


            # -----------------------------------------------
            # VISIBILITY + VEHICLES
            # -----------------------------------------------

            with gr.Row():

                visibility = gr.Slider(

                    minimum=50,

                    maximum=2000,

                    value=500,

                    step=10,

                    label="👁️ Visibility (meters)"
                )


                vehicles_involved = gr.Slider(

                    minimum=1,

                    maximum=5,

                    value=2,

                    step=1,

                    label="🚙 Vehicles Involved"
                )


            # -----------------------------------------------
            # HOUR
            # -----------------------------------------------

            hour = gr.Slider(

                minimum=0,

                maximum=23,

                value=12,

                step=1,

                label="🕐 Hour of Day (0–23)"
            )


            # -----------------------------------------------
            # PREDICT BUTTON
            # -----------------------------------------------

            predict_btn = gr.Button(

                "🚀 Predict Severity",

                elem_id="predict-btn"
            )


            # -----------------------------------------------
            # QUICK EXAMPLES
            # -----------------------------------------------

            gr.HTML("""
            <div class="section-head"
                 style="margin-top:14px;">

                ⚡ Quick Examples

            </div>
            """)


            with gr.Row():

                btn1 = gr.Button(
                    "🌧️ Rainy Highway",
                    elem_classes="ex-btn"
                )

                btn2 = gr.Button(
                    "🌫️ Foggy Road",
                    elem_classes="ex-btn"
                )

                btn3 = gr.Button(
                    "🌙 Night Driving",
                    elem_classes="ex-btn"
                )


            with gr.Row():

                btn4 = gr.Button(
                    "🚦 Heavy Traffic",
                    elem_classes="ex-btn"
                )

                btn5 = gr.Button(
                    "⛈️ Dangerous Highway",
                    elem_classes="ex-btn"
                )


        # ====================================================
        # RIGHT SIDE — OUTPUT
        # ====================================================

        with gr.Column(
            scale=5,
            elem_classes="right-panel"
        ):


            gr.HTML("""
            <div class="section-head">
                🚦 Prediction Result
            </div>
            """)


            # -----------------------------------------------
            # INITIAL RESULT
            # -----------------------------------------------

            result_html = gr.HTML(

                value="""

                <div style="
                    text-align:center;
                    padding:45px 20px;
                    background:#f8fbff;
                    border:2px dashed #bfdbfe;
                    border-radius:16px;
                ">

                    <div style="
                        font-size:48px;
                        margin-bottom:10px;
                    ">
                        🚗
                    </div>

                    <div style="
                        color:#2563eb;
                        font-size:20px;
                        font-weight:800;
                    ">
                        Ready for Prediction
                    </div>

                    <div style="
                        color:#64748b;
                        font-size:14px;
                        margin-top:8px;
                        line-height:1.6;
                    ">
                        Select the accident conditions on the left<br>
                        and click <b style="color:#2563eb;">
                        Predict Severity
                        </b>
                    </div>

                </div>

                """
            )


            # -----------------------------------------------
            # PROBABILITY SECTION
            # -----------------------------------------------

            gr.HTML("""
            <div class="section-head"
                 style="margin-top:14px;">

                📊 Prediction Probabilities

            </div>
            """)


            prob_table = gr.Dataframe(

                headers=[
                    "Severity",
                    "Probability (%)"
                ],

                interactive=False,

                wrap=True
            )


    # ========================================================
    # FOOTER
    # ========================================================

    gr.HTML("""
    <div id="app-footer">

        🛡️
        <b style="color:#2563eb;">
            Drive Safe! Your Safety Is Our Priority.
        </b>

        &nbsp; • &nbsp;

        Built with Python, XGBoost & Gradio

    </div>
    """)


    # ========================================================
    # INPUT / OUTPUT LISTS
    # ========================================================

    all_inputs = [

        weather,
        road_type,
        traffic_density,
        visibility,
        vehicles_involved,
        hour

    ]


    all_outputs = [

        weather,
        road_type,
        traffic_density,
        visibility,
        vehicles_involved,
        hour,
        result_html,
        prob_table

    ]


    # ========================================================
    # PREDICT BUTTON CONNECTION
    # ========================================================

    predict_btn.click(

        fn=predict,

        inputs=all_inputs,

        outputs=[
            result_html,
            prob_table
        ]

    )


    # ========================================================
    # QUICK EXAMPLE CONNECTIONS
    # ========================================================

    btn1.click(

        fn=example_rainy_highway,

        inputs=None,

        outputs=all_outputs

    )


    btn2.click(

        fn=example_foggy_road,

        inputs=None,

        outputs=all_outputs

    )


    btn3.click(

        fn=example_night_driving,

        inputs=None,

        outputs=all_outputs

    )


    btn4.click(

        fn=example_heavy_traffic,

        inputs=None,

        outputs=all_outputs

    )


    btn5.click(

        fn=example_dangerous,

        inputs=None,

        outputs=all_outputs

    )


# ============================================================
# 10. LAUNCH
# ============================================================

app.launch(
    share=True,
    debug=True
)